[hinting]
PPEM_MIN = 11
PPEM_MAX = 36
PPEM_LOCK_BOTTOM = 20
CANONICAL_STEM_WIDTH = [[11,30]]
CANONICAL_STEM_WIDTH_DENSE = [[11,30]]
ABSORPTION_LIMIT = 120
STEM_SIDE_MIN_RISE = 36
STEM_SIDE_MIN_DESCENT = 53
STEM_CENTER_MIN_RISE = 36
STEM_CENTER_MIN_DESCENT = 50
STEM_SIDE_MIN_DIST_RISE = 75
STEM_SIDE_MIN_DIST_DESCENT = 75
Y_FUZZ = 8
BLUEZONE_BOTTOM_CENTER = -70
BLUEZONE_BOTTOM_LIMIT = -45
BLUEZONE_TOP_CENTER = 830
BLUEZONE_TOP_LIMIT = 813
RISE = [[11,10],[16,10],[24,0],[36,0]]
SINK = [[11,10],[36,0]]
SINK_DIAGL = [[11,0],[36,0]]
GRAVITY = [[11,0],[36,0]]
CONCENTRATE = [[11,0],[36,0]]
CHEBYSHEV_4 = [[11,0],[36,0]]
CHEBYSHEV_5 = [[11,0],[36,0]]
TOP_CUT = [[11,0],[18,0],[19,1],[36,1]]
BOTTOM_CUT = [[11,0],[36,0]]